In [336]:
import pandas as pd

file_raw_data = "wine.csv"

raw_data = pd.read_csv(file_raw_data)

raw_data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,bad
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,bad
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,bad
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,good
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,bad
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,bad
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,good
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,good
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,bad
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,good

In [337]:
x = raw_data.iloc[:,:11]

x

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

In [338]:
num_features = len(x.columns)

print("Number of Features: {}".format(num_features))

Number of Features: 11

In [339]:
columns = []

for i in range(num_features):
    columns.append("x{}".format(i))
    
x.columns = columns

x

        x0     x1    x2   x3     x4    x5    x6       x7    x8    x9   x10
0      7.4  0.700  0.00  1.9  0.076  11.0  34.0  0.99780  3.51  0.56   9.4
1      7.8  0.880  0.00  2.6  0.098  25.0  67.0  0.99680  3.20  0.68   9.8
2      7.8  0.760  0.04  2.3  0.092  15.0  54.0  0.99700  3.26  0.65   9.8
3     11.2  0.280  0.56  1.9  0.075  17.0  60.0  0.99800  3.16  0.58   9.8
4      7.4  0.700  0.00  1.9  0.076  11.0  34.0  0.99780  3.51  0.56   9.4
...    ...    ...   ...  ...    ...   ...   ...      ...   ...   ...   ...
1594   6.2  0.600  0.08  2.0  0.090  32.0  44.0  0.99490  3.45  0.58  10.5
1595   5.9  0.550  0.10  2.2  0.062  39.0  51.0  0.99512  3.52  0.76  11.2
1596   6.3  0.510  0.13  2.3  0.076  29.0  40.0  0.99574  3.42  0.75  11.0
1597   5.9  0.645  0.12  2.0  0.075  32.0  44.0  0.99547  3.57  0.71  10.2
1598   6.0  0.310  0.47  3.6  0.067  18.0  42.0  0.99549  3.39  0.66  11.0

[1599 rows x 11 columns]

In [340]:
x_normalized = (x - x.min()) / (x.max() - x.min())

x_normalized

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10
0,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846
1,0.283186,0.520548,0.00,0.116438,0.143573,0.338028,0.215548,0.494126,0.362205,0.209581,0.215385
2,0.283186,0.438356,0.04,0.095890,0.133556,0.197183,0.169611,0.508811,0.409449,0.191617,0.215385
3,0.584071,0.109589,0.56,0.068493,0.105175,0.225352,0.190813,0.582232,0.330709,0.149701,0.215385
4,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846
...,...,...,...,...,...,...,...,...,...,...,...
1594,0.141593,0.328767,0.08,0.075342,0.130217,0.436620,0.134276,0.354626,0.559055,0.149701,0.323077
1595,0.115044,0.294521,0.10,0.089041,0.083472,0.535211,0.159011,0.370778,0.614173,0.257485,0.430769
1596,0.150442,0.267123,0.13,0.095890,0.106845,0.394366,0.120141,0.416300,0.535433,0.251497,0.400000
1597,0.115044,0.359589,0.12,0.075342,0.105175,0.436620,0.134276,0.396476,0.653543,0.227545,0.276923
1598,0.123894,0.130137,0.47,0.184932,0.091820,0.239437,0.127208,0.397944,0.511811,0.197605,0.400000

In [341]:
y = raw_data['quality'].replace(['bad'], 0).replace(['good'], 1)

y = y.values

y

array([0, 0, 0, ..., 1, 0, 1])

In [342]:
num_bad = len(raw_data[raw_data.iloc[:, 11] == 'bad'])
num_good = len(raw_data[raw_data.iloc[:, 11] == 'good'])

print("num_bad: {}".format(num_bad))
print ("num_good: {}".format(num_good))

num_bad: 744
num_good: 855

In [343]:
df = x_normalized.copy()
df['y'] = y
# adding or creating a new column
df

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y
0,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846,0
1,0.283186,0.520548,0.00,0.116438,0.143573,0.338028,0.215548,0.494126,0.362205,0.209581,0.215385,0
2,0.283186,0.438356,0.04,0.095890,0.133556,0.197183,0.169611,0.508811,0.409449,0.191617,0.215385,0
3,0.584071,0.109589,0.56,0.068493,0.105175,0.225352,0.190813,0.582232,0.330709,0.149701,0.215385,1
4,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,0.141593,0.328767,0.08,0.075342,0.130217,0.436620,0.134276,0.354626,0.559055,0.149701,0.323077,0
1595,0.115044,0.294521,0.10,0.089041,0.083472,0.535211,0.159011,0.370778,0.614173,0.257485,0.430769,1
1596,0.150442,0.267123,0.13,0.095890,0.106845,0.394366,0.120141,0.416300,0.535433,0.251497,0.400000,1
1597,0.115044,0.359589,0.12,0.075342,0.105175,0.436620,0.134276,0.396476,0.653543,0.227545,0.276923,0
1598,0.123894,0.130137,0.47,0.184932,0.091820,0.239437,0.127208,0.397944,0.511811,0.197605,0.400000,1

In [344]:
def partition_dataset(df, num_a=50, num_b=50, val_a=1, val_b=0):
    df_a = df[df.iloc[:,-1] == val_a].sample(num_a)
    df_b = df[df.iloc[:,-1] == val_b].sample(num_b)
    
    #remove it
    df.drop(df_a.index, inplace=True)
    df.drop(df_b.index, inplace=True)
    
    # samples: df_a and df_b
    # simply combining two
    frames = [df_a, df_b]
    df_validation = pd.concat(frames)
    
    return df, df_validation

training, validation = partition_dataset(df)

In [345]:
training

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y
0,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846,0
1,0.283186,0.520548,0.00,0.116438,0.143573,0.338028,0.215548,0.494126,0.362205,0.209581,0.215385,0
2,0.283186,0.438356,0.04,0.095890,0.133556,0.197183,0.169611,0.508811,0.409449,0.191617,0.215385,0
3,0.584071,0.109589,0.56,0.068493,0.105175,0.225352,0.190813,0.582232,0.330709,0.149701,0.215385,1
4,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,0.141593,0.328767,0.08,0.075342,0.130217,0.436620,0.134276,0.354626,0.559055,0.149701,0.323077,0
1595,0.115044,0.294521,0.10,0.089041,0.083472,0.535211,0.159011,0.370778,0.614173,0.257485,0.430769,1
1596,0.150442,0.267123,0.13,0.095890,0.106845,0.394366,0.120141,0.416300,0.535433,0.251497,0.400000,1
1597,0.115044,0.359589,0.12,0.075342,0.105175,0.436620,0.134276,0.396476,0.653543,0.227545,0.276923,0
1598,0.123894,0.130137,0.47,0.184932,0.091820,0.239437,0.127208,0.397944,0.511811,0.197605,0.400000,1

In [346]:
validation

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y
119,0.212389,0.390411,0.08,0.061644,0.141903,0.295775,0.293286,0.428047,0.472441,0.125749,0.123077,1
1459,0.292035,0.054795,0.35,0.054795,0.070117,0.084507,0.031802,0.331131,0.456693,0.281437,0.538462,1
875,0.371681,0.130137,0.40,0.130137,0.161937,0.084507,0.035336,0.445668,0.448819,0.275449,0.523077,1
271,0.610619,0.041096,0.51,0.212329,0.153589,0.042254,0.060071,0.699706,0.425197,0.383234,0.261538,1
1412,0.318584,0.082192,0.34,0.287671,0.083472,0.098592,0.056537,0.538179,0.377953,0.365269,0.384615,1
...,...,...,...,...,...,...,...,...,...,...,...,...
615,0.442478,0.328767,0.50,0.095890,0.111853,0.380282,0.229682,0.707048,0.598425,0.143713,0.200000,0
112,0.336283,0.328767,0.10,0.089041,0.121870,0.183099,0.371025,0.464758,0.322835,0.197605,0.215385,0
1186,0.176991,0.465753,0.03,0.472603,0.111853,0.070423,0.021201,0.457416,0.614173,0.101796,0.584615,0
272,0.557522,0.171233,0.58,0.212329,0.098497,0.225352,0.208481,0.681351,0.377953,0.269461,0.261538,0
682,0.345133,0.232877,0.31,0.092466,0.110184,0.436620,0.183746,0.582232,0.464567,0.125749,0.215385,0

# KNeighborsClassifier

In [347]:
from sklearn.neighbors import KNeighborsClassifier
# source: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

# turning it into a normal python array
x_training = training.iloc[:,:-1].values
x_validation = validation.iloc[:,:-1].values

# turning it into a normal python array
y_training = training['y'].values
y_validation = validation['y'].values

In [348]:
# turning it into a normal python array
x_training = training.iloc[:,:-1].values
x_validation = validation.iloc[:,:-1].values

# turning it into a normal python array
y_training = training['y'].values
y_validation = validation['y'].values

In [349]:
# the correct parameter depends on experimentation
model = KNeighborsClassifier(n_neighbors=10)

model.fit(x_training, y_training)

# predictions are 'answers' of the models
predictions = model.predict(x_validation)

# 0 or 1 because they are the 'guess' of the values
predictions

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [350]:
cm = confusion_matrix(y_validation, predictions)
tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

print("True Positive: {}".format(tp))
print("True Negative: {}".format(tn))

# predicted as a 1 when actually is a 0
print("False Positive: {}".format(fp))

# predicted as a 0 when actually is a 1
print("False Negative: {}".format(fn))

# bias towards true positives
f1 = tp / (tp + (0.5 * (fp + fn)))

# if data has a bias like more positives than negatives
mcc = ((tn * tp) - (fn * fp)) / math.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))

print("F1: {}".format(f1))
print("MCC: {}".format(mcc))

True Positive: 34
True Negative: 33
False Positive: 16
False Negative: 17
F1: 0.6732673267326733
MCC: 0.3400680204068024

In [351]:
from sklearn.metrics import confusion_matrix
import math

In [352]:
cm = confusion_matrix(y_validation, predictions)
tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

print("True Positive: {}".format(tp))
print("True Negative: {}".format(tn))

# predicted as a 1 when actually is a 0
print("False Positive: {}".format(fp))

# predicted as a 0 when actually is a 1
print("False Negative: {}".format(fn))

# bias towards true positives
f1 = tp / (tp + (0.5 * (fp + fn)))

# if data has a bias like more positives than negatives
mcc = ((tn * tp) - (fn * fp)) / math.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))

print("F1: {}".format(f1))
print("MCC: {}".format(mcc))

True Positive: 34
True Negative: 33
False Positive: 16
False Negative: 17
F1: 0.6732673267326733
MCC: 0.3400680204068024

# GaussianNB

In [353]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(x_training, y_training)

predictions = model.predict(x_validation)

predictions

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [354]:
cm = confusion_matrix(y_validation, predictions)
tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

print("True Positive: {}".format(tp))
print("True Negative: {}".format(tn))

# predicted as a 1 when actually is a 0
print("False Positive: {}".format(fp))

# predicted as a 0 when actually is a 1
print("False Negative: {}".format(fn))

# bias towards true positives
f1 = tp / (tp + (0.5 * (fp + fn)))

# if data has a bias like more positives than negatives
mcc = ((tn * tp) - (fn * fp)) / math.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))

print("F1: {}".format(f1))
print("MCC: {}".format(mcc))

True Positive: 42
True Negative: 39
False Positive: 8
False Negative: 11
F1: 0.8155339805825242
MCC: 0.6211190222681673

# LogisticRegression

In [355]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x_training, y_training)

predictions = model.predict(x_validation)

predictions

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [356]:
cm = confusion_matrix(y_validation, predictions)
tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

print("True Positive: {}".format(tp))
print("True Negative: {}".format(tn))

# predicted as a 1 when actually is a 0
print("False Positive: {}".format(fp))

# predicted as a 0 when actually is a 1
print("False Negative: {}".format(fn))

# bias towards true positives
f1 = tp / (tp + (0.5 * (fp + fn)))

# if data has a bias like more positives than negatives
mcc = ((tn * tp) - (fn * fp)) / math.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))

print("F1: {}".format(f1))
print("MCC: {}".format(mcc))

True Positive: 41
True Negative: 36
False Positive: 9
False Negative: 14
F1: 0.780952380952381
MCC: 0.5427204202399745

# Decision Tree

In [357]:
from sklearn import tree
# https://scikit-learn.org/stable/modules/tree.html

model = tree.DecisionTreeClassifier()

model.fit(x_training, y_training)

predictions = model.predict(x_validation)

predictions

array([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [358]:
cm = confusion_matrix(y_validation, predictions)
tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

print("True Positive: {}".format(tp))
print("True Negative: {}".format(tn))

# predicted as a 1 when actually is a 0
print("False Positive: {}".format(fp))

# predicted as a 0 when actually is a 1
print("False Negative: {}".format(fn))

# bias towards true positives
f1 = tp / (tp + (0.5 * (fp + fn)))

# if data has a bias like more positives than negatives
mcc = ((tn * tp) - (fn * fp)) / math.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))

print("F1: {}".format(f1))
print("MCC: {}".format(mcc))

True Positive: 35
True Negative: 38
False Positive: 15
False Negative: 12
F1: 0.7216494845360825
MCC: 0.4608302423279951

# Quadratic Discriminative Analysis

In [359]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
# https://scikit-learn.org/stable/modules/generated/sklearn.discriminant_analysis.QuadraticDiscriminantAnalysis.html

In [360]:
model = QuadraticDiscriminantAnalysis()

model.fit(x_training, y_training)

predictions = model.predict(x_validation)

predictions

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [361]:
cm = confusion_matrix(y_validation, predictions)
tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

print("True Positive: {}".format(tp))
print("True Negative: {}".format(tn))

# predicted as a 1 when actually is a 0
print("False Positive: {}".format(fp))

# predicted as a 0 when actually is a 1
print("False Negative: {}".format(fn))

# bias towards true positives
f1 = tp / (tp + (0.5 * (fp + fn)))

# if data has a bias like more positives than negatives
mcc = ((tn * tp) - (fn * fp)) / math.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))

print("F1: {}".format(f1))
print("MCC: {}".format(mcc))

True Positive: 35
True Negative: 42
False Positive: 15
False Negative: 8
F1: 0.7526881720430108
MCC: 0.5453710851915744