In [1]:
import pandas as pd

# Wine

In [23]:
file_wine_data = "wine.csv"

wine_data = pd.read_csv(file_wine_data)

wine_data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,bad
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,bad
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,bad
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,good
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,bad
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,bad
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,good
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,good
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,bad
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,good

In [24]:
# Labels
x_wine = wine_data.iloc[:,:11]

x_wine

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

In [33]:
# How many features do we have?

wine_num_features = len(x_wine.columns)

print("Number of Features :{}".format(wine_num_features))

Number of Features :11

In [26]:
wine_columns = []

# Label all x-features
for i in range(wine_num_features):
    wine_columns.append("x{}".format(i))
    
x_wine.columns = wine_columns

x_wine

        x0     x1    x2   x3     x4    x5    x6       x7    x8    x9   x10
0      7.4  0.700  0.00  1.9  0.076  11.0  34.0  0.99780  3.51  0.56   9.4
1      7.8  0.880  0.00  2.6  0.098  25.0  67.0  0.99680  3.20  0.68   9.8
2      7.8  0.760  0.04  2.3  0.092  15.0  54.0  0.99700  3.26  0.65   9.8
3     11.2  0.280  0.56  1.9  0.075  17.0  60.0  0.99800  3.16  0.58   9.8
4      7.4  0.700  0.00  1.9  0.076  11.0  34.0  0.99780  3.51  0.56   9.4
...    ...    ...   ...  ...    ...   ...   ...      ...   ...   ...   ...
1594   6.2  0.600  0.08  2.0  0.090  32.0  44.0  0.99490  3.45  0.58  10.5
1595   5.9  0.550  0.10  2.2  0.062  39.0  51.0  0.99512  3.52  0.76  11.2
1596   6.3  0.510  0.13  2.3  0.076  29.0  40.0  0.99574  3.42  0.75  11.0
1597   5.9  0.645  0.12  2.0  0.075  32.0  44.0  0.99547  3.57  0.71  10.2
1598   6.0  0.310  0.47  3.6  0.067  18.0  42.0  0.99549  3.39  0.66  11.0

[1599 rows x 11 columns]

In [45]:
x_wine_mean = x_wine.mean()
x_wine_std = x_wine.mean()
x_wine_standardized = (x_wine - x_wine_mean)/x_wine_std

x_wine_standardized

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10
0,-0.110538,0.326208,-1.000000,-0.251617,-0.131096,-0.307083,-0.268310,0.001057,0.060066,-0.149129,-0.098147
1,-0.062459,0.667233,-1.000000,0.024104,0.120428,0.574811,0.441859,0.000053,-0.033558,0.033201,-0.059770
2,-0.062459,0.439883,-0.852385,-0.094062,0.051831,-0.055113,0.162095,0.000254,-0.015437,-0.012381,-0.059770
3,0.346213,-0.469517,1.066607,-0.251617,-0.142529,0.070871,0.291217,0.001257,-0.045638,-0.118740,-0.059770
4,-0.110538,0.326208,-1.000000,-0.251617,-0.131096,-0.307083,-0.268310,0.001057,0.060066,-0.149129,-0.098147
...,...,...,...,...,...,...,...,...,...,...,...
1594,-0.254775,0.136750,-0.704770,-0.212228,0.028965,1.015758,-0.053108,-0.001853,0.041946,-0.118740,0.007389
1595,-0.290834,0.042021,-0.630963,-0.133451,-0.291158,1.456705,0.097534,-0.001632,0.063087,0.154754,0.074548
1596,-0.242755,-0.033762,-0.520252,-0.094062,-0.131096,0.826781,-0.139189,-0.001010,0.032885,0.139560,0.055360
1597,-0.290834,0.222006,-0.557156,-0.212228,-0.142529,1.015758,-0.053108,-0.001281,0.078187,0.078783,-0.021393
1598,-0.278815,-0.412679,0.734473,0.417990,-0.233993,0.133864,-0.096148,-0.001261,0.023825,0.002813,0.055360

In [38]:
# Binary Classification
y_wine = wine_data['quality'].replace(['bad'], 0).replace(['good'], 1)

y_wine = y_wine.values

y_wine

array([0, 0, 0, ..., 1, 0, 1])

In [43]:
num_bad = len(wine_data[wine_data.iloc[:, 11] == 'bad'])
num_good = len(wine_data[wine_data.iloc[:, 11] == 'good'])

print("num_bad: {}".format(num_bad))
print ("num_good: {}".format(num_good))

num_bad: 744
num_good: 855

In [48]:
df_wine = x_wine_standardized.copy()
df_wine['y_wine'] = y_wine
# adding or creating a new column
df_wine

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y_wine
0,-0.110538,0.326208,-1.000000,-0.251617,-0.131096,-0.307083,-0.268310,0.001057,0.060066,-0.149129,-0.098147,0
1,-0.062459,0.667233,-1.000000,0.024104,0.120428,0.574811,0.441859,0.000053,-0.033558,0.033201,-0.059770,0
2,-0.062459,0.439883,-0.852385,-0.094062,0.051831,-0.055113,0.162095,0.000254,-0.015437,-0.012381,-0.059770,0
3,0.346213,-0.469517,1.066607,-0.251617,-0.142529,0.070871,0.291217,0.001257,-0.045638,-0.118740,-0.059770,1
4,-0.110538,0.326208,-1.000000,-0.251617,-0.131096,-0.307083,-0.268310,0.001057,0.060066,-0.149129,-0.098147,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,-0.254775,0.136750,-0.704770,-0.212228,0.028965,1.015758,-0.053108,-0.001853,0.041946,-0.118740,0.007389,0
1595,-0.290834,0.042021,-0.630963,-0.133451,-0.291158,1.456705,0.097534,-0.001632,0.063087,0.154754,0.074548,1
1596,-0.242755,-0.033762,-0.520252,-0.094062,-0.131096,0.826781,-0.139189,-0.001010,0.032885,0.139560,0.055360,1
1597,-0.290834,0.222006,-0.557156,-0.212228,-0.142529,1.015758,-0.053108,-0.001281,0.078187,0.078783,-0.021393,0
1598,-0.278815,-0.412679,0.734473,0.417990,-0.233993,0.133864,-0.096148,-0.001261,0.023825,0.002813,0.055360,1

In [70]:
def partition_dataset(df, num_a=20, num_b=20, val_a=1, val_b=0):
    df_a = df[df.iloc[:,-1] == val_a].sample(num_a)
    df_b = df[df.iloc[:,-1] == val_b].sample(num_b)
    
    #remove it
    df.drop(df_a.index, inplace=True)
    df.drop(df_b.index, inplace=True)
    
    # samples: df_a and df_b
    # simply combining two
    frames = [df_a, df_b]
    df_validation = pd.concat(frames)
    
    return df, df_validation

wine_training, wine_validation = partition_dataset(df_wine)

In [53]:
wine_training

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y_wine
0,-0.110538,0.326208,-1.000000,-0.251617,-0.131096,-0.307083,-0.268310,0.001057,0.060066,-0.149129,-0.098147,0
1,-0.062459,0.667233,-1.000000,0.024104,0.120428,0.574811,0.441859,0.000053,-0.033558,0.033201,-0.059770,0
2,-0.062459,0.439883,-0.852385,-0.094062,0.051831,-0.055113,0.162095,0.000254,-0.015437,-0.012381,-0.059770,0
3,0.346213,-0.469517,1.066607,-0.251617,-0.142529,0.070871,0.291217,0.001257,-0.045638,-0.118740,-0.059770,1
4,-0.110538,0.326208,-1.000000,-0.251617,-0.131096,-0.307083,-0.268310,0.001057,0.060066,-0.149129,-0.098147,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,-0.254775,0.136750,-0.704770,-0.212228,0.028965,1.015758,-0.053108,-0.001853,0.041946,-0.118740,0.007389,0
1595,-0.290834,0.042021,-0.630963,-0.133451,-0.291158,1.456705,0.097534,-0.001632,0.063087,0.154754,0.074548,1
1596,-0.242755,-0.033762,-0.520252,-0.094062,-0.131096,0.826781,-0.139189,-0.001010,0.032885,0.139560,0.055360,1
1597,-0.290834,0.222006,-0.557156,-0.212228,-0.142529,1.015758,-0.053108,-0.001281,0.078187,0.078783,-0.021393,0
1598,-0.278815,-0.412679,0.734473,0.417990,-0.233993,0.133864,-0.096148,-0.001261,0.023825,0.002813,0.055360,1

In [54]:
wine_validation

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y_wine
452,-0.182657,0.060967,-0.889289,-0.330394,-0.039633,0.133864,-0.246790,0.000053,0.038926,-0.042770,-0.040582,1
1275,-0.038420,0.354627,-0.188119,-0.094062,-0.142529,-0.181098,0.743143,0.000134,-0.021477,-0.179517,-0.088553,1
1003,-0.182657,-0.317950,0.180918,-0.291005,-0.233993,-0.748030,-0.827838,-0.003960,0.014764,-0.164323,0.228055,1
853,0.117837,-0.317950,0.439244,-0.409171,-0.085365,1.582690,0.183616,-0.000227,0.047986,0.109172,0.045766,1
568,0.177936,-0.052708,0.808281,0.024104,1.858236,-0.685038,-0.569594,0.002261,-0.000336,0.200336,0.026578,1
500,-0.062459,-0.014817,-0.077408,-0.251617,-0.073932,-0.118106,-0.182229,0.001659,0.035905,-0.012381,-0.136524,1
115,0.129857,-0.242167,0.144014,-0.133451,0.028965,-0.181098,0.334257,-0.000147,-0.072819,-0.042770,0.007389,1
1498,-0.206696,0.695652,-0.852385,-0.094062,-0.222560,-0.559053,-0.720236,-0.000930,0.066107,-0.118740,0.036172,1
1323,0.093798,-0.317950,0.439244,-0.291005,-0.314023,0.322841,0.183616,-0.001803,-0.039598,0.245919,0.055360,1
1313,-0.158617,-0.317950,-0.225023,-0.094062,-0.016767,0.259849,0.398818,-0.001170,0.026845,-0.179517,-0.030988,1
1236,-0.062459,0.042021,-1.000000,-0.330394,-0.199694,-0.559053,-0.634155,-0.000157,-0.015437,-0.027576,-0.098147,1
605,-0.002360,0.136750,-0.520252,0.024104,-0.028200,-0.622045,-0.483513,0.001659,-0.000336,-0.103546,-0.117335,1
1506,-0.182657,0.534613,-0.815482,-0.212228,-0.199694,-0.622045,-0.698716,-0.001130,0.060066,0.002813,0.036172,1
1417,-0.122558,-0.355842,0.217822,-0.015285,-0.268292,0.322841,-0.203750,-0.001552,0.011744,0.169948,0.160896,1
144,-0.374973,-0.355842,-1.000000,-0.291005,-0.428353,0.700796,0.355778,-0.005163,0.111409,0.200336,0.343186,1
1549,-0.110538,-0.317950,0.107111,-0.291005,-0.153962,0.070871,-0.483513,-0.002565,-0.021477,0.063589,0.093737,1
59,-0.122558,-0.261112,0.144014,-0.054674,-0.153962,-0.433068,-0.010067,-0.000548,0.029865,-0.179517,-0.098147,1
118,0.057738,0.042021,-0.852385,-0.133451,0.360520,-0.118106,0.205136,-0.000548,-0.030538,-0.088352,0.045766,1
1161,0.057738,-0.147437,0.586859,-0.448560,-0.131096,-0.244091,-0.548074,-0.001241,-0.030538,0.139560,-0.021393,1
1454,0.406311,-0.147437,1.324932,-0.133451,-0.165395,-0.559053,-0.505034,0.003003,-0.030538,0.048395,0.045766,1
160,-0.086499,0.799854,-0.889289,-0.212228,0.028965,-0.559053,-0.569594,-0.000849,-0.033558,-0.149129,-0.078959,0
1181,0.177936,-0.261112,0.586859,-0.350088,-0.222560,-0.685038,-0.763277,-0.001973,-0.036578,-0.301070,0.093737,0
157,-0.146597,-0.185329,0.549955,1.166373,-0.188261,0.763788,1.754596,0.000555,0.032885,0.078783,0.007389,0
620,-0.002360,0.023075,-0.114311,0.339212,-0.131096,0.007879,1.410272,0.000856,-0.012417,-0.073158,-0.098147,0
621,-0.014380,0.060967,-0.151215,0.339212,-0.108230,-0.118106,1.238109,0.000856,-0.009397,-0.057964,-0.098147,0
582,0.406311,-0.071654,0.808281,-0.133451,-0.051066,-0.685038,-0.677196,0.003264,-0.036578,-0.346652,-0.117335,0
1583,-0.254775,-0.128492,0.070207,-0.172839,-0.153962,1.015758,1.108988,-0.000970,0.005704,-0.057964,-0.059770,0
931,-0.110538,0.155696,-0.963096,-0.212228,-0.153962,-0.181098,-0.182229,0.000736,0.051006,-0.012381,-0.059770,0
1564,-0.134578,0.316735,-0.520252,-0.212228,-0.131096,-0.244091,-0.569594,-0.001291,-0.006376,-0.179517,-0.030988,0
572,0.226015,-0.545300,0.808281,-0.054674,-0.142529,-0.370076,-0.397432,0.001057,-0.051678,-0.073158,-0.002205,0
264,0.502469,0.060967,0.808281,-0.054674,-0.268292,-0.685038,-0.418952,0.003164,-0.069799,0.321889,0.045766,0
766,0.057738,0.117804,-0.335734,0.142269,0.017532,-0.244091,0.592501,0.000635,-0.051678,-0.179517,-0.098147,0
561,0.081778,-0.166383,0.808281,-0.054674,-0.108230,0.637803,1.603954,0.001057,-0.024497,-0.118740,-0.117335,0
1533,-0.038420,-0.261112,0.107111,-0.251617,-0.153962,1.015758,0.807704,0.000425,0.023825,-0.073158,-0.136524,0
1051,0.021679,-0.128492,1.177318,-0.448560,3.733238,0.007879,-0.031587,0.000274,-0.084900,1.036014,-0.117335,0
78,-0.194676,0.420938,-0.557156,-0.212228,-0.016767,-0.244091,0.721623,-0.000950,0.020805,-0.209905,-0.030988,0
832,0.250054,-0.166383,0.549955,-0.409171,0.657777,1.141743,0.032974,0.001578,0.020805,0.306695,-0.050176,0
93,-0.074479,-0.071654,-0.040504,-0.251617,-0.291158,-0.433068,-0.332871,-0.000147,0.023825,-0.027576,-0.078959,0
1484,-0.182657,0.724071,-0.778578,-0.212228,-0.314023,-0.748030,-0.763277,-0.000829,0.066107,-0.027576,0.045766,0
55,-0.074479,0.174642,-0.852385,0.496767,-0.039633,0.574811,-0.031587,0.001057,0.008724,-0.194711,-0.088553,0

# Citrus

In [55]:
file_citrus_data = "citrus.csv"

citrus_data = pd.read_csv(file_citrus_data)

citrus_data

            name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]

In [60]:
# Labels
x_citrus = citrus_data.iloc[:,1:6]

x_citrus

      diameter  weight  red  green  blue
0         2.96   86.76  172     85     2
1         3.91   88.05  166     78     3
2         4.42   95.17  156     81     2
3         4.47   95.60  163     81     4
4         4.48   95.76  161     72     9
...        ...     ...  ...    ...   ...
9995     15.35  253.89  149     77    20
9996     15.41  254.67  148     68     7
9997     15.59  256.50  168     82    20
9998     15.92  260.14  142     72    11
9999     16.45  261.51  152     74     2

[10000 rows x 5 columns]

In [61]:
# How many features do we have?

citrus_num_features = len(x_citrus.columns)

print("Number of Features :{}".format(citrus_num_features))

Number of Features :5

In [62]:
citrus_columns = []

# Label all x-features
for i in range(citrus_num_features):
    citrus_columns.append("x{}".format(i))
    
x_citrus.columns = citrus_columns

x_citrus

         x0      x1   x2  x3  x4
0      2.96   86.76  172  85   2
1      3.91   88.05  166  78   3
2      4.42   95.17  156  81   2
3      4.47   95.60  163  81   4
4      4.48   95.76  161  72   9
...     ...     ...  ...  ..  ..
9995  15.35  253.89  149  77  20
9996  15.41  254.67  148  68   7
9997  15.59  256.50  168  82  20
9998  15.92  260.14  142  72  11
9999  16.45  261.51  152  74   2

[10000 rows x 5 columns]

In [63]:
x_citrus_mean = x_citrus.mean()
x_citrus_std = x_citrus.mean()
x_citrus_standardized = (x_citrus - x_citrus_mean)/x_citrus_std

x_citrus_standardized

            x0        x1        x2        x3        x4
0    -0.703279 -0.504372  0.117988  0.118265 -0.823993
1    -0.608047 -0.497003  0.078988  0.026173 -0.735990
2    -0.556923 -0.456329  0.013989  0.065641 -0.823993
3    -0.551910 -0.453873  0.059489  0.065641 -0.647986
4    -0.550908 -0.452959  0.046489 -0.052764 -0.207970
...        ...       ...       ...       ...       ...
9995  0.538741  0.450379 -0.031510  0.013017  0.760068
9996  0.544756  0.454835 -0.038010 -0.105388 -0.383976
9997  0.562800  0.465289  0.091988  0.078797  0.760068
9998  0.595880  0.486083 -0.077010 -0.052764 -0.031963
9999  0.649010  0.493909 -0.012011 -0.026452 -0.823993

[10000 rows x 5 columns]

In [65]:
# Binary Classification
y_citrus = citrus_data['name'].replace(['orange'], 0).replace(['grapefruit'], 1)

y_citrus = y_citrus.values

y_citrus

array([0, 0, 0, ..., 1, 1, 1])

In [66]:
# Size of each population/demographic based on y

num_orange = len(citrus_data[citrus_data.iloc[:, 0] == 'orange'])
num_grapefruit = len(citrus_data[citrus_data.iloc[:, 0] == 'grapefruit'])

print("num_orange: {}".format(num_orange))
print ("num_grapefruit: {}".format(num_grapefruit))

num_bad: 5000
num_good: 5000

In [67]:
df_citrus = x_citrus_standardized.copy()
df_citrus['y_citrus'] = y_citrus
# adding or creating a new column
df_citrus

            x0        x1        x2        x3        x4  y_citrus
0    -0.703279 -0.504372  0.117988  0.118265 -0.823993         0
1    -0.608047 -0.497003  0.078988  0.026173 -0.735990         0
2    -0.556923 -0.456329  0.013989  0.065641 -0.823993         0
3    -0.551910 -0.453873  0.059489  0.065641 -0.647986         0
4    -0.550908 -0.452959  0.046489 -0.052764 -0.207970         0
...        ...       ...       ...       ...       ...       ...
9995  0.538741  0.450379 -0.031510  0.013017  0.760068         1
9996  0.544756  0.454835 -0.038010 -0.105388 -0.383976         1
9997  0.562800  0.465289  0.091988  0.078797  0.760068         1
9998  0.595880  0.486083 -0.077010 -0.052764 -0.031963         1
9999  0.649010  0.493909 -0.012011 -0.026452 -0.823993         1

[10000 rows x 6 columns]

In [71]:
citrus_training, citrus_validation = partition_dataset(df_citrus)

In [73]:
citrus_training

            x0        x1        x2        x3        x4  y_citrus
0    -0.703279 -0.504372  0.117988  0.118265 -0.823993         0
1    -0.608047 -0.497003  0.078988  0.026173 -0.735990         0
2    -0.556923 -0.456329  0.013989  0.065641 -0.823993         0
3    -0.551910 -0.453873  0.059489  0.065641 -0.647986         0
4    -0.550908 -0.452959  0.046489 -0.052764 -0.207970         0
...        ...       ...       ...       ...       ...       ...
9995  0.538741  0.450379 -0.031510  0.013017  0.760068         1
9996  0.544756  0.454835 -0.038010 -0.105388 -0.383976         1
9997  0.562800  0.465289  0.091988  0.078797  0.760068         1
9998  0.595880  0.486083 -0.077010 -0.052764 -0.031963         1
9999  0.649010  0.493909 -0.012011 -0.026452 -0.823993         1

[9880 rows x 6 columns]

In [74]:
citrus_validation

            x0        x1        x2        x3        x4  y_citrus
5782  0.024491  0.015134 -0.005511  0.065641 -0.119966         1
7735  0.162827  0.141155  0.026989 -0.092232  0.320051         1
9044  0.259061  0.222617  0.091988 -0.289573  0.672064         1
7844  0.169844  0.147039 -0.057510 -0.065920 -0.823993         1
5375 -0.028638 -0.031481  0.007489 -0.079076  0.320051         1
6235  0.067596  0.052209 -0.083510  0.091953 -0.207970         1
6863  0.108696  0.091797 -0.103010  0.144577  0.496057         1
8309  0.202925  0.173716  0.007489 -0.394821 -0.735990         1
6025  0.048550  0.035814  0.065989 -0.144856  0.672064         1
7075  0.121727  0.103794  0.150488 -0.092232  0.848071         1
8943  0.251042  0.215076 -0.077010 -0.013296  1.112081         1
9078  0.262069  0.225530  0.078988  0.052485 -0.823993         1
6576  0.090652  0.075288 -0.038010 -0.079076 -0.119966         1
8426  0.210944  0.180857  0.072489 -0.158012  1.376091         1
5612  0.005445 -0.001204 -0.155009 -0.092232  0.320051         1
8469  0.213952  0.183199  0.000989 -0.105388  0.496057         1
9881  0.393388  0.345210 -0.018511 -0.250105  0.496057         1
7108  0.123732  0.106136 -0.044510 -0.013296  0.496057         1
5406 -0.023626 -0.025997  0.013989 -0.000139  0.936074         1
7053  0.120725  0.102423 -0.103010 -0.092232  1.024078         1
2879 -0.125875 -0.107288 -0.122509 -0.079076 -0.823993         0
3431 -0.090789 -0.075468  0.046489 -0.026452  0.144044         0
2199 -0.166974 -0.144077  0.020489 -0.052764 -0.471980         0
2664 -0.139909 -0.120712  0.169987 -0.171168 -0.647986         0
1222 -0.235140 -0.200861 -0.090010 -0.144856  0.232047         0
226  -0.366460 -0.308544  0.078988  0.105109 -0.207970         0
2286 -0.161962 -0.139107 -0.044510  0.131421 -0.647986         0
2969 -0.119860 -0.102261 -0.018511 -0.092232 -0.823993         0
4228 -0.024628 -0.015829 -0.038010  0.078797 -0.823993         0
1304 -0.229126 -0.196176 -0.005511  0.065641 -0.823993         0
1822 -0.193038 -0.163671 -0.044510 -0.000139 -0.823993         0
194  -0.376484 -0.315627  0.117988  0.118265  0.408054         0
3464 -0.088784 -0.073526  0.026989  0.013017 -0.823993         0
2822 -0.128882 -0.110887  0.052989 -0.026452 -0.735990         0
3192 -0.106828 -0.089122 -0.005511  0.091953 -0.823993         0
4551  0.018476  0.016276  0.091988  0.276138 -0.823993         0
245  -0.360445 -0.304773  0.007489 -0.039608 -0.119966         0
2968 -0.119860 -0.102261  0.091988  0.144577 -0.823993         0
250  -0.358440 -0.303859  0.046489  0.170889 -0.823993         0
3050 -0.115850 -0.098490 -0.018511  0.118265 -0.823993         0

# Heart Disease

In [76]:
file_heart_disease_data = "heart_disease_.csv"

heart_disease_data = pd.read_csv(file_heart_disease_data, low_memory=False)

heart_disease_data

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,0.0,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [77]:
# Labels
# remove the y
x_heart_disease = heart_disease_data.iloc[:,1:]

x_heart_disease

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [79]:
# How many features do we have?

heartdisease_num_features = len(x_heart_disease.columns)

print("Number of Features: {}".format(heartdisease_num_features))

Number of Features: 21

In [80]:
heartdisease_columns = []

# Label all x-features
for i in range(heartdisease_num_features):
    heartdisease_columns.append("x{}".format(i))
    
x_heart_disease.columns = heartdisease_columns

x_heart_disease

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20
0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [81]:
x_heartdisease_mean = x_heart_disease.mean()
x_heartdisease_std = x_heart_disease.mean()
x_heartdisease_standardized = (x_heart_disease - x_heartdisease_mean)/x_heartdisease_std

x_heartdisease_standardized

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20
0,1.330996,1.357818,0.038778,0.409326,1.256478,-1.0,-1.000000,-1.000000,-1.000000,0.232408,...,0.051467,-1.000000,0.990927,4.651896,2.536001,4.944464,-1.000000,0.120501,-0.207989,-0.504450
1,-1.000000,-1.000000,-1.000000,-0.119171,1.256478,-1.0,-1.000000,0.321801,-1.000000,-1.000000,...,-1.000000,10.879742,0.194556,-1.000000,-1.000000,-1.000000,-1.000000,-0.128499,0.188017,-0.834817
2,1.330996,1.357818,0.038778,-0.013472,-1.000000,-1.0,-1.000000,-1.000000,0.576651,-1.000000,...,0.051467,10.879742,0.990927,8.419826,6.072001,4.944464,-1.000000,0.120501,-0.207989,0.321468
3,1.330996,-1.000000,0.038778,-0.048705,-1.000000,-1.0,-1.000000,0.321801,0.576651,0.232408,...,0.051467,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,-1.000000,0.369502,-0.405992,-0.008899
4,1.330996,1.357818,0.038778,-0.154404,-1.000000,-1.0,-1.000000,0.321801,0.576651,0.232408,...,0.051467,-1.000000,-0.203629,-0.058017,-1.000000,-1.000000,-1.000000,0.369502,-0.009986,-0.339266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.330996,1.357818,0.038778,0.585492,-1.000000,-1.0,-1.000000,-1.000000,0.576651,0.232408,...,0.051467,-1.000000,0.194556,-1.000000,0.178667,-1.000000,1.270961,-0.377499,0.188017,0.156284
253676,1.330996,1.357818,0.038778,-0.365803,-1.000000,-1.0,5.735791,-1.000000,-1.000000,-1.000000,...,0.051467,-1.000000,0.592742,-1.000000,-1.000000,4.944464,-1.000000,0.369502,-0.603994,-0.339266
253677,-1.000000,-1.000000,0.038778,-0.013472,-1.000000,-1.0,-1.000000,0.321801,0.576651,-1.000000,...,0.051467,-1.000000,-0.601815,-1.000000,-1.000000,-1.000000,-1.000000,-0.751000,-0.009986,-0.669633
253678,1.330996,-1.000000,0.038778,-0.189638,-1.000000,-1.0,-1.000000,-1.000000,0.576651,0.232408,...,0.051467,-1.000000,0.194556,-1.000000,-1.000000,-1.000000,1.270961,-0.128499,-0.009986,-0.834817
253679,1.330996,1.357818,0.038778,-0.119171,-1.000000,-1.0,5.735791,0.321801,0.576651,-1.000000,...,0.051467,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,-1.000000,0.120501,0.188017,-0.669633

In [94]:
# Binary Classification

y_heartdisease = heart_disease_data['HeartDiseaseorAttack']

y_heartdisease = y_heartdisease.values

y_heartdisease

array([0., 0., 0., ..., 0., 0., 1.])

In [96]:
# Size of each population/demographic based on y

num_zero = len(heart_disease_data[heart_disease_data.iloc[:, 0] == 0.0])
num_one = len(heart_disease_data[heart_disease_data.iloc[:, 0] == 1.0])

print("num_zero: {}".format(num_zero))
print ("num_one: {}".format(num_one))

num_zero: 229787
num_one: 23893

In [97]:
df_heartdisease = x_heartdisease_standardized.copy()
df_heartdisease['y_heartdisease'] = y_heartdisease
# adding or creating a new column
df_heartdisease

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x12,x13,x14,x15,x16,x17,x18,x19,x20,y_heartdisease
0,1.330996,1.357818,0.038778,0.409326,1.256478,-1.0,-1.000000,-1.000000,-1.000000,0.232408,...,-1.000000,0.990927,4.651896,2.536001,4.944464,-1.000000,0.120501,-0.207989,-0.504450,0.0
1,-1.000000,-1.000000,-1.000000,-0.119171,1.256478,-1.0,-1.000000,0.321801,-1.000000,-1.000000,...,10.879742,0.194556,-1.000000,-1.000000,-1.000000,-1.000000,-0.128499,0.188017,-0.834817,0.0
2,1.330996,1.357818,0.038778,-0.013472,-1.000000,-1.0,-1.000000,-1.000000,0.576651,-1.000000,...,10.879742,0.990927,8.419826,6.072001,4.944464,-1.000000,0.120501,-0.207989,0.321468,0.0
3,1.330996,-1.000000,0.038778,-0.048705,-1.000000,-1.0,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,-1.000000,0.369502,-0.405992,-0.008899,0.0
4,1.330996,1.357818,0.038778,-0.154404,-1.000000,-1.0,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,-0.203629,-0.058017,-1.000000,-1.000000,-1.000000,0.369502,-0.009986,-0.339266,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.330996,1.357818,0.038778,0.585492,-1.000000,-1.0,-1.000000,-1.000000,0.576651,0.232408,...,-1.000000,0.194556,-1.000000,0.178667,-1.000000,1.270961,-0.377499,0.188017,0.156284,0.0
253676,1.330996,1.357818,0.038778,-0.365803,-1.000000,-1.0,5.735791,-1.000000,-1.000000,-1.000000,...,-1.000000,0.592742,-1.000000,-1.000000,4.944464,-1.000000,0.369502,-0.603994,-0.339266,0.0
253677,-1.000000,-1.000000,0.038778,-0.013472,-1.000000,-1.0,-1.000000,0.321801,0.576651,-1.000000,...,-1.000000,-0.601815,-1.000000,-1.000000,-1.000000,-1.000000,-0.751000,-0.009986,-0.669633,0.0
253678,1.330996,-1.000000,0.038778,-0.189638,-1.000000,-1.0,-1.000000,-1.000000,0.576651,0.232408,...,-1.000000,0.194556,-1.000000,-1.000000,-1.000000,1.270961,-0.128499,-0.009986,-0.834817,0.0
253679,1.330996,1.357818,0.038778,-0.119171,-1.000000,-1.0,5.735791,0.321801,0.576651,-1.000000,...,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,-1.000000,0.120501,0.188017,-0.669633,1.0

In [98]:
heartdisease_training, heartdisease_validation = partition_dataset(df_heartdisease)

In [99]:
heartdisease_training

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x12,x13,x14,x15,x16,x17,x18,x19,x20,y_heartdisease
0,1.330996,1.357818,0.038778,0.409326,1.256478,-1.0,-1.000000,-1.000000,-1.000000,0.232408,...,-1.000000,0.990927,4.651896,2.536001,4.944464,-1.000000,0.120501,-0.207989,-0.504450,0.0
1,-1.000000,-1.000000,-1.000000,-0.119171,1.256478,-1.0,-1.000000,0.321801,-1.000000,-1.000000,...,10.879742,0.194556,-1.000000,-1.000000,-1.000000,-1.000000,-0.128499,0.188017,-0.834817,0.0
2,1.330996,1.357818,0.038778,-0.013472,-1.000000,-1.0,-1.000000,-1.000000,0.576651,-1.000000,...,10.879742,0.990927,8.419826,6.072001,4.944464,-1.000000,0.120501,-0.207989,0.321468,0.0
3,1.330996,-1.000000,0.038778,-0.048705,-1.000000,-1.0,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,-1.000000,0.369502,-0.405992,-0.008899,0.0
4,1.330996,1.357818,0.038778,-0.154404,-1.000000,-1.0,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,-0.203629,-0.058017,-1.000000,-1.000000,-1.000000,0.369502,-0.009986,-0.339266,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.330996,1.357818,0.038778,0.585492,-1.000000,-1.0,-1.000000,-1.000000,0.576651,0.232408,...,-1.000000,0.194556,-1.000000,0.178667,-1.000000,1.270961,-0.377499,0.188017,0.156284,0.0
253676,1.330996,1.357818,0.038778,-0.365803,-1.000000,-1.0,5.735791,-1.000000,-1.000000,-1.000000,...,-1.000000,0.592742,-1.000000,-1.000000,4.944464,-1.000000,0.369502,-0.603994,-0.339266,0.0
253677,-1.000000,-1.000000,0.038778,-0.013472,-1.000000,-1.0,-1.000000,0.321801,0.576651,-1.000000,...,-1.000000,-0.601815,-1.000000,-1.000000,-1.000000,-1.000000,-0.751000,-0.009986,-0.669633,0.0
253678,1.330996,-1.000000,0.038778,-0.189638,-1.000000,-1.0,-1.000000,-1.000000,0.576651,0.232408,...,-1.000000,0.194556,-1.000000,-1.000000,-1.000000,1.270961,-0.128499,-0.009986,-0.834817,0.0
253679,1.330996,1.357818,0.038778,-0.119171,-1.000000,-1.0,5.735791,0.321801,0.576651,-1.000000,...,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,-1.000000,0.120501,0.188017,-0.669633,1.0

In [100]:
heartdisease_validation

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x12,x13,x14,x15,x16,x17,x18,x19,x20,y_heartdisease
83053,1.330996,-1.000000,0.038778,0.092228,1.256478,-1.000000,-1.000000,-1.000000,0.576651,0.232408,...,-1.000000,0.592742,-0.372012,-1.000000,4.944464,-1.000000,-0.003999,-0.009986,0.156284,1.0
120256,1.330996,1.357818,0.038778,0.092228,-1.000000,-1.000000,5.735791,-1.000000,0.576651,-1.000000,...,-1.000000,0.194556,-1.000000,-0.057066,-1.000000,-1.000000,0.618502,0.188017,-0.339266,1.0
90613,1.330996,1.357818,0.038778,-0.154404,1.256478,-1.000000,-1.000000,0.321801,-1.000000,0.232408,...,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,1.270961,0.369502,0.188017,0.156284,1.0
200032,1.330996,1.357818,0.038778,-0.224871,-1.000000,23.648271,-1.000000,0.321801,-1.000000,0.232408,...,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,1.270961,0.618502,0.188017,-0.008899,1.0
72431,1.330996,1.357818,0.038778,-0.224871,-1.000000,-1.000000,5.735791,-1.000000,0.576651,0.232408,...,-1.000000,0.592742,-1.000000,-0.057066,-1.000000,1.270961,0.618502,-0.207989,-0.008899,1.0
144460,1.330996,-1.000000,0.038778,-0.189638,1.256478,23.648271,-1.000000,-1.000000,0.576651,-1.000000,...,-1.000000,-0.601815,0.255977,-1.000000,-1.000000,-1.000000,0.618502,-0.009986,-0.504450,1.0
68928,-1.000000,-1.000000,0.038778,-0.154404,1.256478,-1.000000,-1.000000,-1.000000,0.576651,0.232408,...,-1.000000,0.194556,-1.000000,-1.000000,4.944464,-1.000000,0.245001,-0.207989,-0.174083,1.0
60362,1.330996,1.357818,0.038778,0.338860,1.256478,-1.000000,5.735791,-1.000000,0.576651,0.232408,...,-1.000000,0.990927,2.139942,-0.057066,-1.000000,1.270961,0.120501,-0.009986,-0.504450,1.0
60390,1.330996,1.357818,0.038778,0.162694,1.256478,-1.000000,5.735791,0.321801,-1.000000,-1.000000,...,-1.000000,-0.203629,-1.000000,0.178667,-1.000000,1.270961,0.369502,0.188017,0.321468,1.0
61863,-1.000000,1.357818,0.038778,0.021761,1.256478,23.648271,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,0.194556,-1.000000,0.178667,-1.000000,-1.000000,0.369502,-0.009986,-0.174083,1.0
132137,1.330996,1.357818,0.038778,-0.224871,1.256478,-1.000000,5.735791,-1.000000,-1.000000,0.232408,...,-1.000000,0.592742,8.419826,-0.057066,-1.000000,1.270961,-0.003999,-0.207989,0.321468,1.0
204535,1.330996,-1.000000,0.038778,0.127461,-1.000000,-1.000000,-1.000000,0.321801,-1.000000,0.232408,...,10.879742,0.990927,-1.000000,0.414400,4.944464,1.270961,0.494002,0.188017,0.321468,1.0
190528,1.330996,1.357818,0.038778,0.550258,-1.000000,23.648271,5.735791,-1.000000,0.576651,0.232408,...,10.879742,0.990927,-1.000000,6.072001,4.944464,1.270961,0.120501,-0.009986,-0.174083,1.0
66551,-1.000000,1.357818,0.038778,0.056994,1.256478,-1.000000,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,0.194556,-1.000000,-1.000000,-1.000000,1.270961,0.120501,-0.009986,-0.008899,1.0
228715,-1.000000,1.357818,0.038778,0.127461,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,0.592742,-1.000000,3.714668,4.944464,-1.000000,0.369502,-0.405992,0.156284,1.0
169620,1.330996,1.357818,0.038778,0.056994,1.256478,-1.000000,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,0.194556,-1.000000,-1.000000,-1.000000,1.270961,0.494002,-0.009986,-0.008899,1.0
161511,1.330996,1.357818,0.038778,0.127461,-1.000000,-1.000000,5.735791,0.321801,-1.000000,0.232408,...,-1.000000,0.194556,-1.000000,-0.528533,-1.000000,1.270961,0.369502,-0.207989,-0.504450,1.0
9532,1.330996,1.357818,0.038778,0.127461,1.256478,-1.000000,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,0.194556,-1.000000,-1.000000,-1.000000,-1.000000,0.245001,-0.009986,0.321468,1.0
80281,-1.000000,-1.000000,0.038778,-0.189638,1.256478,-1.000000,-1.000000,-1.000000,0.576651,0.232408,...,-1.000000,0.592742,-1.000000,-0.528533,-1.000000,1.270961,0.120501,-0.009986,0.321468,1.0
190690,1.330996,1.357818,0.038778,0.127461,1.256478,-1.000000,5.735791,-1.000000,0.576651,0.232408,...,-1.000000,0.194556,-1.000000,-1.000000,-1.000000,1.270961,-0.003999,-0.207989,0.156284,1.0
117192,-1.000000,-1.000000,0.038778,0.197927,1.256478,-1.000000,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,-0.203629,-1.000000,-0.057066,-1.000000,1.270961,-0.501999,0.188017,-0.174083,0.0
212370,-1.000000,-1.000000,0.038778,-0.224871,1.256478,-1.000000,-1.000000,-1.000000,-1.000000,0.232408,...,-1.000000,0.194556,-1.000000,-1.000000,-1.000000,-1.000000,0.120501,-0.405992,-0.504450,0.0
180278,1.330996,-1.000000,0.038778,0.021761,1.256478,-1.000000,5.735791,-1.000000,-1.000000,0.232408,...,-1.000000,-0.601815,-1.000000,-1.000000,-1.000000,1.270961,0.245001,-0.603994,-0.669633,0.0
32116,-1.000000,1.357818,0.038778,-0.295337,1.256478,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,0.194556,-1.000000,-1.000000,-1.000000,-1.000000,0.120501,-0.207989,-0.008899,0.0
40982,-1.000000,-1.000000,0.038778,-0.224871,1.256478,-1.000000,-1.000000,0.321801,-1.000000,0.232408,...,-1.000000,-0.601815,2.767930,-1.000000,-1.000000,-1.000000,-0.751000,-0.207989,0.156284,0.0
222387,-1.000000,-1.000000,0.038778,-0.330570,-1.000000,-1.000000,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,-1.000000,-0.252999,0.188017,0.321468,0.0
12483,1.330996,-1.000000,0.038778,-0.154404,-1.000000,-1.000000,5.735791,-1.000000,0.576651,0.232408,...,10.879742,0.592742,3.709913,1.357334,4.944464,-1.000000,0.618502,-0.603994,-0.669633,0.0
134622,-1.000000,-1.000000,0.038778,-0.260104,1.256478,-1.000000,-1.000000,0.321801,-1.000000,0.232408,...,-1.000000,-0.601815,-1.000000,-1.000000,-1.000000,-1.000000,0.120501,0.188017,0.156284,0.0
23971,1.330996,1.357818,0.038778,-0.083938,-1.000000,-1.000000,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,-1.000000,0.245001,-0.009986,0.156284,0.0
204400,-1.000000,1.357818,0.038778,-0.154404,-1.000000,-1.000000,-1.000000,0.321801,-1.000000,0.232408,...,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,-1.000000,0.245001,0.188017,0.321468,0.0
250763,1.330996,1.357818,0.038778,0.021761,-1.000000,-1.000000,-1.000000,0.321801,-1.000000,0.232408,...,-1.000000,0.194556,-1.000000,-0.057066,-1.000000,1.270961,-0.501999,0.188017,0.156284,0.0
105416,1.330996,1.357818,0.038778,-0.119171,1.256478,-1.000000,5.735791,0.321801,0.576651,-1.000000,...,-1.000000,0.194556,-1.000000,1.357334,-1.000000,1.270961,0.618502,-0.405992,-0.008899,0.0
83673,1.330996,1.357818,0.038778,0.233160,1.256478,-1.000000,5.735791,-1.000000,-1.000000,-1.000000,...,-1.000000,0.990927,8.419826,6.072001,4.944464,-1.000000,0.120501,-0.009986,-0.834817,0.0
115929,-1.000000,-1.000000,0.038778,-0.189638,1.256478,-1.000000,-1.000000,-1.000000,0.576651,0.232408,...,-1.000000,-0.601815,-1.000000,-1.000000,-1.000000,-1.000000,-0.377499,-0.009986,-0.339266,0.0
9737,-1.000000,-1.000000,0.038778,-0.119171,-1.000000,-1.000000,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,-1.000000,0.245001,0.188017,0.321468,0.0
111190,1.330996,1.357818,0.038778,0.761657,-1.000000,-1.000000,-1.000000,-1.000000,0.576651,0.232408,...,-1.000000,0.990927,2.139942,6.072001,-1.000000,-1.000000,-0.377499,-0.009986,0.156284,0.0
178947,-1.000000,-1.000000,0.038778,0.092228,1.256478,-1.000000,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,-0.203629,-1.000000,-1.000000,-1.000000,1.270961,-0.128499,-0.009986,0.321468,0.0
130114,-1.000000,-1.000000,0.038778,0.761657,1.256478,-1.000000,-1.000000,0.321801,0.576651,0.232408,...,-1.000000,0.194556,3.709913,-1.000000,-1.000000,-1.000000,-0.626500,-0.009986,-0.504450,0.0
138703,1.330996,-1.000000,0.038778,0.338860,1.256478,23.648271,-1.000000,-1.000000,0.576651,0.232408,...,-1.000000,0.194556,-0.372012,-0.764267,-1.000000,1.270961,-0.501999,-0.009986,0.321468,0.0
185221,-1.000000,-1.000000,0.038778,-0.154404,-1.000000,-1.000000,-1.000000,0.321801,-1.000000,-1.000000,...,-1.000000,-0.601815,-1.000000,-0.764267,-1.000000,1.270961,-0.252999,0.188017,0.321468,0.0